### ISSUE TITLE
hostaddr with Postgres 9.4

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#202]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/202) by Vít Ondruch (Bitbucket: [vo_x](https://bitbucket.org/vo_x), ).**

----------------------------------------

I observe this error on Fedora Rawhide:

~~~
  1) PG::Connection can retrieve it's connection parameters for the established connection
     Failure/Error: expect( @conn.hostaddr ).to eq( nil ) if @conn.server_version >= 9_04_00
     NoMethodError:
       undefined method `hostaddr' for #<PG::Connection:0x000000030dc8e0>
     # ./spec/pg/connection_spec.rb:166:in `block (2 levels) in <top (required)>'
     # ./spec/helpers.rb:29:in `block in included'
~~~

although I have postgres 9.4 installed:

~~~
$ rpm -q postgresql-devel
postgresql-devel-9.4.0-1.fc22.x86_64
~~~

This is apparently due to:

~~~
checking for PQhostaddr()... no
~~~

And it seems tath PQhostadd was reverted from 9.4:

http://www.postgresql.org/message-id/E1Xum2y-00026b-Oj@gemulon.postgresql.org

This test was introduced by 3a7b6a1d1cfe9f4403f22372ccb49c73a036f896
