### ISSUE TITLE
Gem does not build under JRuby on OS X 10.7.3 with Xcode 4.3.1 and updated CLI tools

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#115]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/115) by Ryan Payne (Bitbucket: [paynerc](https://bitbucket.org/paynerc), GitHub: [paynerc](https://github.com/paynerc)).**

----------------------------------------

It appears that the gem does not want to build correctly using JRuby 1.6.7 on OS X 10.7.3 with the latest Xcode 4.3.1 and command line tools installed. 

Looking at the output in mkmf.log, there appears to be a few things going on here.

1. Clang is now the default compiler

2. The clang compiler is throwing out an error because PQconnectdb is defined as having one argument, however the call in conftest.c is calling a no argument method:

conftest.c:5:23: error: too few arguments to function call, expected 1, have 0
int t() { PQconnectdb(); return 0; }
          ~~~~~~~~~~~ ^
/usr/include/libpq-fe.h:234:1: note: 'PQconnectdb' declared here
extern PGconn *PQconnectdb(const char *conninfo);

3. It appears that clang is having issues with finding the JavaVM framework (however I think is an issue to be filed with JRuby, and not a pg gem issue).

I was able to compile and install the gem by setting the CC environment variable to "gcc" and the installing the gem.
